name: Build and Deploy code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test: 
    runs-on: ubuntu-lastest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Python version 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
