name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:/home/ubuntu/Documents/Gross-2-Salary"
          pytest

  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -f docker/frontend.Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/gross-2-salary-frontend:latest .
          docker build -f docker/backend.Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/gross-2-salary-backend:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gross-2-salary-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gross-2-salary-backend:latest